from .attendance import (
    AttendanceRecordResponse,
    AttendanceRecordShort,
    AttendanceListResponse,
    AttendanceFilter,
    AttendanceStatsResponse,
    PersonInfo,
    PersonListResponse,
    PersonFilter,
    DailyAttendanceSummary,
    PersonHistoryResponse,
    LateArrivalPerson,
    LateArrivalsResponse,
    EmployeeAttendanceRecord,
    EmployeeAttendanceSummary,
    EmployeeAttendanceListResponse,
)

from .common import (
    PaginationParams,
    PaginatedResponse,
    SuccessResponse,
    ErrorResponse,
    HealthCheckResponse,
)

from .faculty import (
    FacultyBasic,
    FacultyWithStats,
    FacultyListResponse,
    FacultyStats,
    FacultyFilter,
    DepartmentBasic,
    DepartmentListResponse,
    get_faculty_slug,
    get_faculty_name,
)

from .employees import (
    EmployeeBase,
    EmployeeListResponse,
    LateEmployeeSummary,
    LateEmployeesResponse,
    PlatonusFaculty,
    PlatonusFacultyListResponse,
    PlatonusSubdivision,
    PlatonusSubdivisionListResponse,
    TopLateEmployee,
    DivisionLateStats,
    DailyLateStats,
    LateTimeDistribution,
    LateStatisticsResponse,
    EmployeeAttendanceHistory,
    EmployeeAttendanceHistoryRecord,
)

from .work_schedule import (
    WorkScheduleRuleBase,
    WorkScheduleRuleCreate,
    WorkScheduleRuleUpdate,
    WorkScheduleRuleResponse,
    WorkScheduleRuleListResponse,
    WorkScheduleRuleSummary,
)

__all__ = [
    # Attendance schemas
    "AttendanceRecordResponse",
    "AttendanceRecordShort",
    "AttendanceListResponse",
    "AttendanceFilter",
    "AttendanceStatsResponse",
    "PersonInfo",
    "PersonListResponse",
    "PersonFilter",
    "DailyAttendanceSummary",
    "PersonHistoryResponse",
    "LateArrivalPerson",
    "LateArrivalsResponse",
    "EmployeeAttendanceRecord",
    "EmployeeAttendanceSummary",
    "EmployeeAttendanceListResponse",
    # Common schemas
    "PaginationParams",
    "PaginatedResponse",
    "SuccessResponse",
    "ErrorResponse",
    "HealthCheckResponse",
    # Faculty schemas
    "FacultyBasic",
    "FacultyWithStats",
    "FacultyListResponse",
    "FacultyStats",
    "FacultyFilter",
    "DepartmentBasic",
    "DepartmentListResponse",
    "get_faculty_slug",
    "get_faculty_name",
    # Employee schemas
    "EmployeeBase",
    "EmployeeListResponse",
    "LateEmployeeSummary",
    "LateEmployeesResponse",
    "PlatonusFaculty",
    "PlatonusFacultyListResponse",
    "PlatonusSubdivision",
    "PlatonusSubdivisionListResponse",
    "TopLateEmployee",
    "DivisionLateStats",
    "DailyLateStats",
    "LateTimeDistribution",
    "LateStatisticsResponse",
    "EmployeeAttendanceHistory",
    "EmployeeAttendanceHistoryRecord",
    # Work Schedule schemas
    "WorkScheduleRuleBase",
    "WorkScheduleRuleCreate",
    "WorkScheduleRuleUpdate",
    "WorkScheduleRuleResponse",
    "WorkScheduleRuleListResponse",
    "WorkScheduleRuleSummary",
]
